### ISSUE TITLE
Options are reset upon reloading the options screen (Firefox)

### ISSUE THREAD

**Issue by bsvka** [ueokande/vimmatic#117]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

I can set the options successfully, but upon returning to the options page they are reset to the default ones.

### Expected behavior

The options not to reset when reloading the options page.

### Steps to reproduce

1. Open plugin-settings
2. Open the "Options"-tab
3. Modify options (e.g. set `properties.smoothscroll` to `true`)
4. Close plugin-settings
5. Test if smoothscroll is enabled (it is for me)
6. Reopen plugin-settings
7. Reopen "Options"-tab
8. The options are now reverted to the default (check visually)
9. Close plugin-settings
10. Test if smoothscroll is still enabled (it still is for me)

At this point, the plugin still seems to use the user-set options, while displaying the default options.

11. Reopen plugin-settings
12. Reopen "Options"-tab
13. Change something minor (add a space, remove it again)
14. Test if smoothscroll is enabled (it no longer is)

This bug can be worked around by storing the entire configuration in a separate text-file and always reapplying the whole thing.

### Environment

- Browser: Firefox
- Vimmatic version: 0.1.1

**Comment by ueokande** [comment]
Thanks for your report, I have been able to reproduce it.  I will fix it on next release.
