### ISSUE TITLE
Support for Firefox 112.0 with flatpak

### ISSUE THREAD

**Issue by notdodo** [ueokande/vimmatic#123]
### The issue is already reported or known issue?

- [x] I have searched the existing issues on github
- [x] I am using the latest version

### Current behavior

None of the keymaps works

### Expected behavior

Extension works

### Steps to reproduce

1. Install firefox 112.0 with flatpak

### Environment

- OS: Ubuntu 22.04.02
- Browser: Firefox 112.0 (flatpka)
- Vimmatic version: 0.2.0

**Comment by InvisibleRain** [comment]
Works for me on Firefox 113.0 with flatpak. You need to go to extension settings and manually give it all the permission it is asking for
