### ISSUE TITLE
Firefox Addon Description links to wrong Github Repo (404)

### ISSUE THREAD

**Issue by SVNKoch** [ueokande/vimmatic#124]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

The github link at https://addons.mozilla.org/en-US/firefox/addon/vimmatic/ links to
https://github.com/ueokande/vimmaticis
resulting in a 404.

### Expected behavior

it should link to
https://github.com/ueokande/vimmatic (without "is" at end)

### Steps to reproduce

https://addons.mozilla.org/en-US/firefox/addon/vimmatic/

**Comment by ueokande** [comment]
Thanks for your report.  I fixed it.
