### ISSUE TITLE
opening clipboard’s URL in new tab appends http:// to local files

### ISSUE THREAD

**Issue by SVNKoch** [ueokande/vimmatic#126]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

opens http://file///D:/test/test.html

### Expected behavior

should open file:///D:/test/test.html

### Steps to reproduce

1. Have a local file path copied to clipboard like `file:///D:/test/test.html`
1.1. eg. by opening any local file in the browser and `y`: yanking the url to clipboard
2. `p`/ `P` to open url in (new) tab

### Environment

- Browser: FF 110.0.1
- Vimmatic version: 0.2.0

**Comment by ueokande** [comment]
Thanks for your reporting.  Firefox inhibit add-ons to open `file://` for [security reasons](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create). I will replace the error message with a clear one.
