### ISSUE TITLE
Allow to select items from list in console mode

### ISSUE THREAD

**Issue by Busyvar** [ueokande/vimmatic#131]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Description

Hi, 
I think this feature might improve user experience for full keyboard interaction.
When using : + any command which propose autocompletion list there is no way to select item of the list with keyboard.

1. Arrow keys are focused on text input, so getting up/down will just move text cursor to start/end
2. Ctrl+n and Ctrl+p are still catched by browser to open new window and print current page.

It would be a more vim-like experience to catch those inputs in console mode so user would be able to select items without mouse interaction.

Best Regards,
Busyvar

**Comment by ueokande** [comment]
Thanks for your feedback.  Pressing <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> works as you expected.  We have no guides of such feature on the document.  I will improve it.

**Comment by Busyvar** [comment]
Fine, i thought it would be the same shortcut as in shell, that's i didn't found it.
