### ISSUE TITLE
Options screen broken

### ISSUE THREAD

**Issue by ava5627** [ueokande/vimmatic#233]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

The options screen shows an empty text box that is unable to be written in.
Previously set configuration stays in effect but is unable to be changed
![image](https://github.com/ueokande/vimmatic/assets/40039652/49250c76-4151-47a3-9a2b-b43b1ececa4d)

### Expected behavior

Options screen shows configuration json

### Steps to reproduce

1. Open options screen

### Environment

- OS: MacOS 13.6 and Arch Linux
- Browser: Firefox 117.0.1 and Chrome 114.0.5735.198
- Vimmatic version: 0.5.2

**Comment by svenk-ct** [comment]
Happens here, too. Empty textentry which is not writable.
macOS 13.6, Firefox 118.0.1, Vimmatic 0.5.2
![CleanShot 2023-10-06 at 08 48 41](https://github.com/ueokande/vimmatic/assets/123731255/5871a8cf-e172-469e-8023-1196d22d0209)

**Comment by gabeklavans** [comment]
Having the same problem here, v0.5.2

**Comment by ueokande** [comment]
Sorry for late reply.  I will fix in #267 and release new version soon.
