### ISSUE TITLE
Opening an image with a shortcut like f follow

### ISSUE THREAD

**Issue by tim-kilian** [ueokande/vimmatic#239]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Description

I sometimes need to inspect an image on the page to increase the size for example. My current behaviour is to switch to the mouse, right click, open image in new tab. I really felt in love with the follow command f, and had the idea, that it would be nice to open that image with a follow command without switching to my mouse.

**Comment by TrTai** [comment]
Don't know if this was added after the post, but you can open an image or open in a new tab with ;i and ;I respectively then hit the corresponding marker key https://ueokande.github.io/vimmatic/keymaps

**Comment by ueokande** [comment]
Yes, you can now open an image with <kbd>;</kbd><kbd>i</kbd> and <kbd>;</kbd><kbd>I</kbd>.  They are supported since [v0.6.0](https://github.com/ueokande/vimmatic/releases/tag/v0.6.0) (released last month).
