### ISSUE TITLE
Cannot see/edit/access Preferences JSON

### ISSUE THREAD

**Issue by PolyMMA** [ueokande/vimmatic#258]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

When I navigate to Manage Extension>>Preferences 

I see a small empty square where the JSON usually is displayed.

![image](https://github.com/ueokande/vimmatic/assets/29153251/62b3ecdb-c28c-44c6-82dc-c086c66c234a)

### Expected behavior

Manage Extension>>Preferences should take me to a view where I can edit the Preferences JSON.

### Steps to reproduce

1. Manage Extension
2. Preferences
3. the JSON location is just a small empty box

### Environment

- OS: System:
  Kernel: 6.1.55-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
    clocksource: tsc Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36
    info: xfce4-panel wm: xfwm v: 4.18.0 vt: 7 dm: LightDM v: 1.32.0
    Distro: Manjaro Linux base: Arch Linux

- Browser: Firefox 119.0
Build ID 	20231023160744
Distribution ID 	Manjaro
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
OS 	Linux 6.1.55-1-MANJARO 
OS Theme 	Matcha-dark-sea / Matcha-sea

- Vimmatic version: v0.5.2

*ALL OTHER ADDONS/EXTENSIONS DEACTIVATED!*

**Comment by PolyMMA** [comment]
Same thing on 

Browser: Google Chrome Version 118.0.5993.117 (Official Build) (64-bit)

OS VERSION: Linux: 6.1.55-1-MANJAR

![image](https://github.com/ueokande/vimmatic/assets/29153251/bb1e35eb-201b-4afe-97b3-75c92e0e475c)

**Comment by PolyMMA** [comment]
Same exact thing on 
--------------------------------------------------
Name 	       Firefox
Version 	118.0.2
Build ID 	20231009140911
Distribution ID 	canonical
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
OS 	Linux 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023
OS Theme 	Adwaita-dark / Adwaita
--------------------------------------------------
Google Chrome
CHROME VERSION     118.0.5993.88
OS VERSION         Linux: 5.15.0-87-generic

-------------------------------------------------
OS: Kernel: 5.15.0-87-generic x86_64 bits: 64 compiler: N/A 
  Desktop: Gnome 3.36.9 wm: gnome-shell dm: GDM3 3.36.3 
  Distro: Ubuntu 20.04.6 LTS (Focal Fossa)

-------------------------------------------------

Vimmatic: v0.5.2

All other addons deactivated

**Comment by PolyMMA** [comment]
btw... been using vimmatic since it was referred to from vim-vixen. Worked great, still works great, but recently I cannot edit the JSON. I can still modify the preferences using :set

**Comment by ryqm** [comment]
Same here

Librewolf 118.0.2-1
OS: 6.5.9-arch2-1 
Desktop: Plasma 5.27.9
Vimmatic: 0.5.2

**Comment by tschoesi** [comment]
Are there any news on this? I would really like to be able to permanently blacklist a page.

**Comment by PolyMMA** [comment]
@ueokande not sure who to tag here nor if it helps but you seem to be the top contributor and I was hoping to at least have this validated as a known bug. Could you take a look?

**Comment by ueokande** [comment]
Sorry for late reply.  I will fix in #267 and release new version soon.

**Comment by PolyMMA** [comment]
> Sorry for late reply. I will fix in #267 and release new version soon.

Thanks. I can confirm from my side that 0.5.3 fixes the issue on Chrome and Firefox. Thanks!
