### ISSUE TITLE
Cannot use vimmatic bindings in settings or new blank tabs in firefox

### ISSUE THREAD

**Issue by AgentAR** [ueokande/vimmatic#297]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

doesn't seem to work in settings or blank new tabs in firefox
but does work in the other tabs that websites are opened in 

### Expected behavior

works on all tabs

### Steps to reproduce

1. Open settings menu
2. Press any vimmatic key binding
3. The extension doesn't seem to work in that tab

### Environment

- OS: ArchLinux
- Browser: Firefox 119.0
- Vimmatic version: 0.5.3

**Comment by agvxov** [comment]
Some pages, such as the built-ins (e.g. settings, default new blank) are not allowed to load extensions at all.
This is the closest i could find to the documentation on the spot: https://discourse.mozilla.org/t/content-scripts-are-not-loaded-in-firefox-on-some-web-pages/60705
However, you could set your new tab as something else than blank.
