### ISSUE TITLE
smooth scroll

### ISSUE THREAD

**Issue by gmankab** [ueokande/vimmatic#315]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Description

please add a smooth scroll feature

**Comment by trevarj** [comment]
It's in the extension preferences. Set `"smoothscroll": true` :
```
 "properties": {
    "hintchars": "abcdefghijklmnopqrstuvwxyz",
    "smoothscroll": true,
    "complete": "sbh",
    "colorscheme": "system"
  },
```

**Comment by gmankab** [comment]
thank you
