### ISSUE TITLE
Extension fills dev console with console.warn

### ISSUE THREAD

**Issue by victorz** [ueokande/vimmatic#351]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

This extension spews the following message:

```
unexpected message format: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    listen WindowMessageListener.ts:46
```

in the dev console, over and over, at least once per second if not more. [The offending line.](https://github.com/ueokande/vimmatic/blob/94b7d7f7613f00dbc2baab0a02ef500e1e19785d/src/content/messaging/WindowMessageListener.ts#L49)

Definitely should not leave a `console.warn` in production. It's flooding my console when I'm trying to do web development, making my job harder during the day. I have to disable the extension for my development.

I don't know whether or not the message itself indicates something seriously wrong, but it's definitely not wanted. I hope the issue can be resolved by either removing the console.warn from this extension, or fixing the issue itself, of trying to parse something as JSON which is not JSON.

### Expected behavior

Don't spew warnings in the user's dev console.

### Steps to reproduce

1. Open any page.
2. Open the dev console.
3. The extension starts to spew warnings in there.

### Environment

- OS: Arch Linux
- Browser: Firefox 122.0.1
- Vimmatic version: 0.6.1

**Comment by hyshka** [comment]
I have the same issue with a similar setup. Let me know if there's any info I can contribute.

**Comment by glutaminefree** [comment]
Hi! Please push this release to Firefox/Chrome extensions stores. Latest version on both is 0.6.1.
