### ISSUE TITLE
Backlist not working on Youtube

### ISSUE THREAD

**Issue by ahmedsamyh** [ueokande/vimmatic#468]
### The issue is already reported or known issue?

- [X] I have searched the existing issues on github
- [X] I am using the latest version

### Current behavior

I have this as my backlist:
```json
  "blacklist": [
    "youtube.com/*",
    "youtube.com"
  ],
```
-------------------------------------
- i open `www.youtube.com`
- vimmatic still works

NOTE: Backlist works on everyother site (that i checked), only youtube doesn't seem to be backlisting... same issue with Vim Vixen

### Expected behavior

- i open `www.youtube.com`
- vimmatic to not work

### Steps to reproduce

1. Add youtube to backlist; eg:
```json
  "blacklist": [
    "youtube.com/*",
    "youtube.com"
  ],
```
2. Open `www.youtube.com`

### Environment

- OS: Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- Browser: Firefox 115.12.0esr (64-bit)
- Vimmatic version: 0.7.1

**Comment by Anonymous3-a** [comment]
Try using "https://www.youtube.com*" instead.

**Comment by ahmedsamyh** [comment]
ok that worked thanks! honestly don't know why i didn't try that before
